name: My Turn Media Group
favicon: null
layout_spectrum: 0.5354131
typography_spectrum: 0.6871838
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: SEO and PPC Marketing Company
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2dfffe'
    - '#000000'
    - '#6f6f6f'
    - '#2e2e2e'
  brandStrength: 0.8726813
  lightness: 0.5508018294349313
  saturation: 0.9375
  rhythmicContrast: 0.6773757149931043
purpose: []
